version: '3.9'

services:
  solace:
    container_name: solace
    image: $PUBSUB_IMAGE
    hostname: $PUBSUB_HOSTNAME
    # volumes:
    #   - "solace:/var/lib/solace"
    shm_size: 1g
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 6592
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    ports:
      #Web transport
      - 8008:8008
      #Web transport over TLS
      - 1443:1443
      #SEMP over TLS
      - 1943:1943
      #MQTT Default VPN
      - 1883:1883
      #AMQP Default VPN over TLS
      - 5671:5671
      #AMQP Default VPN
      - 5672:5672
      #MQTT Default VPN over WebSockets
      - 8005:8000
      #MQTT Default VPN over WebSockets / TLS
      - 8442:8443
      #MQTT Default VPN over TLS
      - 8883:8883
      #SEMP / PubSub+ Manager
      - 8081:8080
      #REST Default VPN
      - 9000:9000
      #REST Default VPN over TLS
      - 9443:9443
      #SMF
      - 55554:55555
      #SMF Compressed
      - 55050:55003
      #SMF over TLS
      - 55443:55443
      #SSH connection to CLI
      - 2222:2222
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
      - webmanager_redirecthttp_enable=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s
      start_interval: 5s
    networks:
      - common-network

  # Jaeger
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    command: ["--memory.max-traces=1000"]
    networks:
      - common-network
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
      - "14268:14268"
      - "14250:14250"


  # Collector
  otel-collector:
    container_name: otel-collector
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    hostname: otelcollector
    networks:
      - common-network
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  # Container uses Python script (in /solace folder) to populate solace broker with queues and topics based on the queues.json file 
  solace-init:
    build:
      context: ./solace/
      dockerfile: Dockerfile
    container_name: solace-init
    restart: "no"
    depends_on:
      solace:
        condition: service_healthy
    networks:
      - common-network

# volumes:
#   solace:

networks:
  common-network:
    external: false
    driver: bridge
